<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SlideFed.PublishCore\SlideFed.PublishCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiquidVictor.Data.YamlFile" Version="1.9.1" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
